stages:
  - build
  - deploy

Build:
  stage: build
  image: docker:latest
  before_script:
      - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}:latest
  after_script:
    - docker logout registry.gitlab.com

#### Ignore.
#deploy:
#  variables:
#    HOME_DIR: /home/johannes/docker/services/jitesoft.web
#  stage: deploy
#  image: alpine
#  before_script:
#    - apk add --no-cache openssh-client
#    - eval $(ssh-agent -s)
#    - echo "${DEPLOY_KEY}" | ssh-add -
#    - mkdir -p ~/.ssh
#    - echo "${JITESOFT_SERVER_KEY}" > ~/.ssh/known_hosts
#  script:
#    - ssh ${DEPLOY_USER}@jitesoft.com 'git pull origin master'
#    - ssh ${DEPLOY_USER}@jitesoft.com 'docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com && cd ${HOME_DIR} && docker pull ${CI_REGISTRY_IMAGE}:latest && docker service update && docker logout registry.gitlab.com'
#  environment:
#    name: Production
#  only:
#    - master
