stages:
  - build
  - image
  - deploy

build:
  stage: build
  image: jitesoft/node-base
  variables:
    NODE_ENV: production
  before_script:
    - npm install -g yarn
  script:
    - yarn install
    - yarn prod
  artifacts:
    paths:
      - dist
      - Dockerfile
    when: on_success
    expire_in: 1 week

page:
  stage: image
  dependencies:
    - build
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - rm dist/index-labs.html
    - mv dist/index-page.html index.html
    - docker build -t ${CI_REGISTRY_IMAGE}-page:latest --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}-page:latest

labs:
  stage: image
  dependencies:
    - build
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - rm dist/index-page.html
    - mv dist/index-labs.html index.html
    - docker build -t ${CI_REGISTRY_IMAGE}-labs:latest --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}-labs:latest

deploy:
  variables:
    HOME_DIR: /home/johannes/docker/services/jitesoft.web
  stage: deploy
  image: jitesoft/alpine-ssh:latest
  before_script:
    - eval $(ssh-agent -s)
    - echo "${DEPLOY_KEY}" | ssh-add -
    - echo "${JITESOFT_SERVER_KEY}" > ~/.ssh/known_hosts
  script:
    - scp  ./docker-compose.yml ${DEPLOY_USER}@jitesoft.com:${HOME_DIR}
    - ssh ${DEPLOY_USER}@jitesoft.com "docker service update jitesoft_web --with-registry-auth && chown --recursive deployer:docker ${HOME_DIR}"
