image: php:7.1.1

cache:
  paths:
  - vendor/

before_script:
  - composer install --prefer-source --no-interaction
  - composer dump-autoload


# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
  - vendor/bin/phpcs -p --report=summary --standard=ruleset.xml

