variables:
  GIT_STRATEGY: "clone"
  GIT_CHECKOUT: "true"
  GIT_DEPTH: "1"

build-php:
  image: jitesoft/composer:latest
  stage: build
  script:
    - composer install --prefer-source --no-interaction
  artifacts:
    paths:
      - vendor/
    expire_in: 2 hrs


build-js:
  image: jitesoft/gulp-bower:latest
  stage: build
  script:
    - npm install
    - gulp default
  artifacts:
    paths:
      - node_modules/
      - public/css/
      - public/js/
    expire_in: 2 hrs

test-php:
  image: jitesoft/composer:latest
  stage: test
  dependencies:
    - build-php
  script:
    - vendor/bin/phpcs -p --report=summary --standard=ruleset.xml app
    - vendor/bin/phpunit --configuration phpunit.xml --colors=never

test-js:
  image: jitesoft/gulp-bower:latest
  stage: test
  dependencies:
    - build-js
  script:
    - npm test


#deploy:
#  stage: deploy
#  dependencies:
#    - build-php
#    - build-js
#  script:
#    - ""
#  environment:
#    name: Production
#  only:
#    - master
