image: jitesoft/composer:latest

cache:
  paths:
    - vendor/

test:
  script:
    - composer install --prefer-source --no-interaction
    - composer dump-autoload
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
    - vendor/bin/phpcs -p --report=summary --standard=ruleset.xml app

