variables:
  GIT_STRATEGY: "clone"
  GIT_CHECKOUT: "true"
  GIT_DEPTH: "1"

build-test-php:
  cache:
    key: build-cache:composer
    paths:
      - vendor/
  image: jitesoft/composer:latest
  stage: build
  script:
    - composer install --prefer-source --no-interaction
    - vendor/bin/phpcs -p --report=summary --standard=ruleset.xml app
    - vendor/bin/phpunit --configuration phpunit.xml --colors=never
    - composer install --prefer-source --no-interaction --no-dev
  artifacts:
    paths:
      - vendor/
    expire_in: 2 hrs

build-js:
  image: jitesoft/gulp-bower:latest
  stage: build
  script:
    - npm install
    - gulp default
  artifacts:
    paths:
      - node_modules/
      - public/css/
      - public/js/
    expire_in: 2 hrs

test-js:
  image: jitesoft/gulp-bower:latest
  stage: test
  dependencies:
    - build-js
  script:
    - npm test

deploy:
  stage: deploy
  image: alpine
  dependencies:
    - build-test-php
    - build-js
  before_script:
    - apk add --no-cache openssh-client tar
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY" > ~/.ssh/known_hosts
  script:
    - echo "$ENV_FILE" > .env
    - cd ../ && tar -zcf web.tar.gz -X ./web/.tarignore web
    - scp web.tar.gz ${DEPLOY_USER}@jitesoft.com:/services/webpage/
    - ssh ${DEPLOY_USER}@jitesoft.com 'tar -xzf /services/webpage/web.tar.gz -C /services/webpage/source --strip-components=1 && rm /services/webpage/web.tar.gz'
    - ssh ${DEPLOY_USER}@jitesoft.com 'docker exec webpage_fpm_1 php artisan deploy:cleanup'
  environment:
    name: Production
  only:
    - master
