cache:
  paths:
    - vendor/
    - node_modules/

variables:
  GIT_STRATEGY: "clone"
  GIT_CHECKOUT: "true"
  GIT_DEPTH: "1"


build-php:
  image: jitesoft/composer:latest
  stage: build
  script:
    - composer install --prefer-source --no-interaction


build-js:
  image: jitesoft/gulp-bower
  stage: build
  script:
    - npm install
    - gulp default
    - npm test

test-php:
  image: jitesoft/composer:latest
  stage: test
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --colors=never
    - vendor/bin/phpcs -p --report=summary --standard=ruleset.xml app


test-js:
  image: jitesoft/gulp-bower
  stage: test
  script:
    - npm test
