##########################################
## Development docker-compose file.
##########################################
version: '2'

services:

  database:
    env_file: .env
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - mysql

  fpm:
    image: jitesoft/php-fpm:latest
    expose:
      - "9000"
    networks:
      default:
        aliases:
          - fpm
          - php
    volumes:
      - "./:/app"

  nginx:
    depends_on:
      - fpm
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./:/app
    networks:
      - default
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
     - redis-data:/data
    networks:
      - default
    ports:
      - "10812:6379"
    command: redis-server --port 6379 --appendonly yes

volumes:
  db-data:
  redis-data:
