version: '2'

services:

    # Data only containers.
    web-data:
        container_name: Jitesoft_web_data
        image: busybox
        volumes:
            - "./:/usr/share/nginx/html"

    nginx-data:
       container_name: Jitesoft_nginx_data
       image: busybox
       volumes:
           - "./nginx:/tmp/nginx"
           - "./:/usr/share/nginx/html"

    mysql-data:
        container_name: Jitesoft_mysql_data
        image: busybox
        volumes:
            - "./storage/database:/var/lib/mysql"

    redis-data:
        container_name: Jitesoft_redis_data
        image: busybox
        volumes:
            - "./storage/redis:/data"

    # Database.
    database:
        container_name: Jitesoft_mysql
        env_file: .env
        image: mysql:5.7
        volumes_from:
            - mysql-data
        networks:
            jitesoft-web-internal:
                aliases:
                    - mysql

    # Php-fpm
    fpm:
        container_name: Jitesoft_fpm
        build:
            context: .
            dockerfile: dockerfiles/php7fpm.docker
        image: php7-fpm:latest
        networks:
            jitesoft-web-internal:
                aliases:
                    - fpm
                    - php
        volumes_from:
            - web-data

    # Nginx
    nginx:
        container_name: Jitesoft_nginx
        depends_on:
            - fpm
        image: nginx:latest
        env_file: .env
        volumes_from:
            - nginx-data
        networks:
            proxy-tier:
                aliases:
                    - jitesoft-web-nginx
            jitesoft-web-internal:
                aliases:
                    - nginx
        expose:
          - 80
        command: /bin/bash -c "cp /tmp/nginx/nginx.conf /etc/nginx/nginx.conf && nginx"

    redis:
        image: redis:alpine
        container_name: Jitesoft_redis
        volumes_from:
            - redis-data
        networks:
            jitesoft-web-internal:
                aliases:
                    - redis
        command: redis-server --port 6379 --appendonly yes

networks:
   jitesoft-web-internal:
   proxy-tier:
      external:
          name: nginx-proxy
