##########################################
## Development docker-compose file.
##########################################
version: '2'

services:

  web-data:
    image: busybox
    volumes:
      - "./:/app"

  nginx-data:
    image: busybox
    volumes:
      - "./nginx/:/etc/nginx/conf.d"

  mysql-data:
    image: busybox
    volumes:
      - "./storage/database:/var/lib/mysql"

  redis-data:
    image: busybox
    volumes:
      - "./storage/redis:/data"

  database:
    env_file: .env
    image: mysql:5.7
    expose:
      - "3306"
    volumes_from:
      - mysql-data
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - mysql

  fpm:
    image: jitesoft/php-fpm:latest
    expose:
      - "9000"
    networks:
      default:
        aliases:
          - fpm
          - php
    volumes_from:
      - web-data

  nginx:
    depends_on:
      - fpm
    image: nginx
    volumes_from:
      - nginx-data
      - web-data
    networks:
      - default
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes_from:
      - redis-data
    networks:
      - default
    ports:
      - "10812:6379"
    command: redis-server --port 6379 --appendonly yes

