version: '3.5'

services:

  database:
    env_file: .env
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql

  fpm:
    image: registry.gitlab.com/jitesoft/web:latest
    networks:
      default:
        aliases:
          - fpm
          - php

  nginx:
    depends_on:
      - fpm
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - web-proxy
      - default
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:jitesoft.com,jitesoft.eu,jitesoft.se,www.jitesoft.com,www.jitesoft.se,www.jitesoft.eu"
        - "traefik.docker.network=web-proxy"
        - "traefik.enable=true"

  redis:
    image: redis:alpine
    volumes:
     - redis-data:/data
    networks:
      - default
    command: redis-server --port 6379 --appendonly yes

networks:
  web-proxy:
    external: true
    name: web-proxy

volumes:
  db-data:
  redis-data:
