version: '3.5'

services:

  web:
    image: registry.gitlab.com/jitesoft/web:latest
    networks:
      web-proxy:
        aliases:
          - jitesoft
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:jitesoft.com,jitesoft.eu,jitesoft.se,www.jitesoft.com,www.jitesoft.se,www.jitesoft.eu"
        - "traefik.docker.network=web-proxy"
        - "traefik.enable=true"

networks:
  web-proxy:
    external: true
    name: web-proxy
